### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by piecioshka** [jhermsmeier/git-branch-select#11]
Hi @jhermsmeier ✋ 

I put incorrect name of branch and I that error ocured:
```
g branch-select
✔ Select a branch: › q
/Users/piecioshka/.nvm/versions/node/v8.9.4/lib/node_modules/git-branch-select/node_modules/command-join/command-join.js:24
    for (let char of command) {
                     ^

TypeError: command is not iterable
```

Maybe you can handle this and display error message without quiting interactive mode?

**Comment by jhermsmeier** [comment]
Oh, sure – thanks for bringing this up; I totally missed that. Fixed the error happening in 2.0.1, and added re-prompting when a non-existent branch is selected in 2.1.0 :)
