### ISSUE TITLE
Branches not showing

### ISSUE THREAD

**Issue by nbonamy** [jhermsmeier/git-branch-select#18]
Hello,

when I run branch-select I get

```
$ git branch-select
? Select a branch: ›
❯   [object Object]
```

git branch works fine so I am really not understanding what is going on here:

```
$ git branch
  feature/***
  feature/$$$
  feature/###
* master
```

Running node v12.7 and git v2.11 on Debian 9.

Thanks!

**Comment by jhermsmeier** [comment]
Interesting. Stupid question: Are you running it in the repo root? I can only reproduce this running it outside of a git repository so far.

**Comment by nbonamy** [comment]
Yes.

```
$ git st
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

$ git bs
✖ Select a branch: › [object Object]
```

**Comment by jhermsmeier** [comment]
Can you run the following, and post the result?
```
git branch --list --all --no-color --sort=-committerdate
```

I also just published `git-branch-select@3.2.2`, which fixes displaying `[object Object]` if `git` doesn't return any branches (although it doesn't look like that's the issue here), and now correctly shows

```
? Select a branch: ›
no matches found
```

**Comment by nbonamy** [comment]
Ran the git branch command. Our repo has a lot of branches so no point in showing them all:

```
$ git branch --list --all --no-color --sort=-committerdate | head -10
  remotes/origin/master
  remotes/origin/HEAD -> origin/master
* master
  remotes/origin/...
  remotes/origin/...
  remotes/origin/...
  remotes/origin/feature/...
  remotes/origin/feature/...
  remotes/origin/release/...
  remotes/origin/bugfix/...
```

Updated to `git-branch-select@3.2.2` and got the result you expected:

```
$ git bs
? Select a branch: ›
no matches found
```

Thanks
Nicolas

**Comment by jhermsmeier** [comment]
Thanks!
Hmm. That shouldn't happen if git lists branches. I'll do some testing.
Does the following print anything for that repo (that's what git-branch-select uses)?

```
git branch --all --format='%(HEAD)|%(refname)|%(refname:lstrip=2)|%(upstream)|%(upstream:remotename)|%(upstream:remoteref)|%(push)'
```

**Comment by nbonamy** [comment]
```
$ git branch --all --format='%(HEAD)|%(refname)|%(refname:lstrip=2)|%(upstream)|%(upstream:remotename)|%(upstream:remoteref)|%(push)'
error: unknown option `format=%(HEAD)|%(refname)|%(refname:lstrip=2)|%(upstream)|%(upstream:remotename)|%(upstream:remoteref)|%(push)'
u
```

😂

**Comment by jhermsmeier** [comment]
Aaaaaha 😆Guess I'll go and make this compatible with "older" versions of git

**Comment by jhermsmeier** [comment]
I've updated it now to read the refs from the `.git` directory instead of shelling out to `git` – which should in theory get around the git version dependency – but had to remove the sorting by latest committer date (for now)
