### ISSUE TITLE
"fatal: missing branch name; try -b"

### ISSUE THREAD

**Issue by tomholford** [jhermsmeier/git-branch-select#19]
First of all, love this tool, have been using it for years and promoting it to other developers. Thanks for your hard work!

So, the list of branches is still rendered:
![image](https://user-images.githubusercontent.com/16504501/81766373-f45d6c00-9510-11ea-9934-06ef798c026f.png)

But selecting fails with the aforementioned error:
![image](https://user-images.githubusercontent.com/16504501/81766413-0808d280-9511-11ea-94e1-b41f100743c5.png)

Just upgraded to `3.2.2` to see if that might do the trick, but no luck.

Here is some metadata that might help, LMK if there are any other diagnostics that would be useful:
```
Linux computer 4.15.0-91-generic #92-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
git version 2.26.2
node v14.1.0
```

**edit**:

Adding one more diagnostic based on the other issue:
![image](https://user-images.githubusercontent.com/16504501/81766708-9b420800-9511-11ea-91da-4357879b0bcf.png)

**Comment by jhermsmeier** [comment]
Hi @tomholford, thanks for the kind words and the lovely bug report! :)

I've rewritten the whole thing in `git-branch-select@4.0.0` now, reading the refs directly from the `.git` directory, and then properly switching between checkout commands depending on whether it's a remote or local branch head.

That should hopefully fix this issue, but I had to sacrifice branch ordering by latest committer date for the time being, will add that back in a later version.

Also added some new command line flags (`--local`, `--remote` and `--tags`) in the process to narrow things down should the need arise.

Hope it'll continue to bring joy :)

**Comment by tomholford** [comment]
@jhermsmeier Thanks for addressing the issue, much appreciated! Unfortunately, after upgrading to `4.0.0`, there appears to be another issue:

![image](https://user-images.githubusercontent.com/16504501/82750055-a259f780-9de8-11ea-8597-f0e289dc5eb1.png)

Perhaps this has something to do with Linux? I think I remember reading something about `fs` not having universal platform support, but maybe that has changed.

**Comment by jhermsmeier** [comment]
Unfortunate indeed – I think I know what this is – I forgot about branches with slashes (`/`) in their names, which causes this read error, as it's trying to read a directory as a file to get the commit hash.
