### ISSUE TITLE
Broken support for branch names with slashes

### ISSUE THREAD

**Issue by jhermsmeier** [jhermsmeier/git-branch-select#20]
Branches with `/` in their names cause it to crash with `EISDIR` as it's trying to read the commit hash from the ref file.

See https://github.com/jhermsmeier/git-branch-select/issues/19#issuecomment-633202764 for details

**Comment by akowalz** [comment]
Any update on a this issue?  the plugin has been broken for me since 4.0.0 and I'd love for a fix here!

**Comment by jhermsmeier** [comment]
You're welcome to send a PR this way, or you can revert to version 3.x.x instead. It was a major version bump for a reason. Otherwise no news on this; don't have time to work on it atm.
