### ISSUE TITLE
[bug] [linux] Filtering shows `[Object object]` in results 

### ISSUE THREAD

**Issue by tomholford** [jhermsmeier/git-branch-select#26]
Noticed this when switching back to Linux from Mac for some dev work.

Viewing the list of branches works on both devices...
```
$ g bs
? Select a branch: › 
❯   master
    roller
    t/linear-release
    t/tx-view-iterate-0
    origin / ja/gh-issue-template
    origin / t/spawn-point-ux
```

... but filtering now shows `[Object object]` in the results on Linux:
```
? Select a branch: › li
❯   [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
```

git-branch-select: 4.0.4
Node: 14.17.0
OS: macOS 12.0.1, Ubuntu 21.04.

**Comment by jhermsmeier** [comment]
It's been a while, but a fix is published in `git-branch-select@4.0.5` now
