### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Deleplace** [jhermsmeier/git-branch-select#4]
First try didn't work for me : 
```
$ sudo npm install --global git-branch-select
$ git branch-select
/usr/local/lib/node_modules/git-branch-select/node_modules/prompt-base/index.js:819
  var prompt = new this(...args);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-branch-select/node_modules/prompt-checkbox/index.js:4:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by jhermsmeier** [comment]
@Deleplace which node version are you running?

**Comment by Deleplace** [comment]
```
$ node -v
v4.2.6
```

Xubuntu 16.04.2 LTS, 64-bit

**Comment by Deleplace** [comment]
I'm not familiar enough with node/npm to decide if "sudo" was necessary for npm install.  Installation didn't work for me without "sudo".

**Comment by jhermsmeier** [comment]
Oh, this looks like a dependency I recently updated (`prompt-list`) isn't compatible with Node v4 anymore :/ If you `npm install --global git-branch-select@1.0.4` (which doesn't have that updated dependency yet), it should work I believe.

**Comment by jhermsmeier** [comment]
Also, `sudo` generally shouldn't be necessary when npm installing anything globally (or locally) – you can `sudo chown -R $(whoami):admin /usr/local/` to avoid having to use `sudo`, if I recall correctly.

**Comment by jhermsmeier** [comment]
@Deleplace I've just downgraded the dependency in question and published `git-branch-select@1.0.6`, which is compatible with Node v4 again, so installing the latest version of this should fix it!

**Comment by Deleplace** [comment]
How quick, thanks Jonas! I installed again and it worked.

**Comment by jhermsmeier** [comment]
@Deleplace glad it works again – thanks for raising this issue! :)
