### ISSUE TITLE
Quick access by first letter

### ISSUE THREAD

**Issue by Deleplace** [jhermsmeier/git-branch-select#6]
When list shows up alphabetically, it would be nice to type the first letter of desired branch, to quick jump to the first entry starting by that letter.

It wouldn't help in all cases (e.g. when all the branches have the same prefix!) but would still be a delight in normal usage.

**Comment by Deleplace** [comment]
#7 (if implemented) would supersede this.

**Comment by jhermsmeier** [comment]
Closing this, as #7 has been implemented :)
