### ISSUE TITLE
Cursor disappears when ctrl+c

### ISSUE THREAD

**Issue by protoEvangelion** [jhermsmeier/git-branch-select#9]
![image](https://user-images.githubusercontent.com/20076677/32342132-c2f50816-bfbc-11e7-9b7d-689d974c85c0.png)

When cancelling the script instead of choosing a branch, the cursor disappears.

Resourcing the terminal doesn't work. I have to close and reopen it.

**Comment by jhermsmeier** [comment]
Yeah, there's a bug in there; you can get the cursor back by running it again and hitting enter straight away (that'll select the current branch you're on, and reset the cursor) – haven't had time to look into so far :/

**Comment by protoEvangelion** [comment]
@jhermsmeier Thanks for the quick response. I work on a project that has a cancel option.  I will look into it and see if I can integrate that ;)

**Comment by jhermsmeier** [comment]
Fixed by #10
